#conCurrentHashMap<String,Map<String,Lease>>中第一个String，某个服务集群的共同的实例名
spring:
  application:
    name: kjxz-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenShdow/config.git
          username: 1158753601@qq.com
          password: ZHEMOshanggan...
          basedir: F:\IDESpringBootWorkSpace\kjxz\logs
#conCurrentHashMap<String,Map<String,Lease>>中第二个String，某个服务自己的项目名
eureka:
  instance:
    hostname: config
  client:
    service-url:
      #指定用这个地址来注册 ,http://eureka2:8001/eureka
      defaultZone: http://eureka1:8000/eureka

server:
  port: 5000