spring:
  application:
    name: kjxz-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenShdow/config.git
          username: 1158753601@qq.com
          password: ZHEMOshanggan...
          basedir: F:\IDESpringBootWorkSpace\kjxz\logs
eureka:
  instance:
    hostname: config
  client:
    service-url:
      #指定用这个地址来注册 ,http://eureka2:8001/eureka
      defaultZone: http://eureka1:8000/eureka
server:
  port: 7000